### ISSUE TITLE
Problem with submodule

### ISSUE THREAD

**Issue by jubalh** [lxde/libfm-qt#81]
```
git submodule update --init --recursive
fatal: No url found for submodule path 'data/translations' in .gitmodules
```

**Comment by luis-pereira** [comment]
why recursive ? there's no nested submodules.

**Comment by jubalh** [comment]
Thats just what my script launches on multiple repos. AFAIK its no harm. So even without `--recursive` the above happens. Wasnt there something that translations was a seperate repo and now isnt?

**Comment by luis-pereira** [comment]
@jubalh 
My recipe is:
```
git submodule init
git submodule update --remote --rebase
```

**Comment by jubalh** [comment]
@luis-pereira I dont think this is error is due to wrong usage of commands, there is a problem with the submodule:
```
git clone https://github.com/lxde/libfm-qt
Cloning into 'libfm-qt'...
remote: Counting objects: 3830, done.
remote: Compressing objects: 100% (54/54), done.
remote: Total 3830 (delta 33), reused 1 (delta 1), pack-reused 3775
Receiving objects: 100% (3830/3830), 1.41 MiB | 740.00 KiB/s, done.
Resolving deltas: 100% (3000/3000), done.
~/src % cd libfm-qt 
~/src/libfm-qt (git)-[master] % git submodule init
fatal: No url found for submodule path 'data/translations' in .gitmodules
```

**Comment by yan12125** [comment]
In other LXQt projects, the translations repo is maintained via a command in ```CMakeLists.txt``` instead of as a submodule. Maybe we cab do the same in libfm-qt?

**Comment by luis-pereira** [comment]
@yan12125 If it isn't, it should.

**Comment by jubalh** [comment]
Now we are getting somewhere :)
I thought I remembered something like this when I said:
> Wasnt there something that translations was a seperate repo and now isnt?

**Comment by yan12125** [comment]
Here it is :) #82
